### ISSUE TITLE
Consider switching from mmap to memmap

### ISSUE THREAD

**Issue by retep998** [vberger/wayland-kbd#6]
`memmap` is actually maintained.

https://github.com/danburkert/memmap-rs

**Comment by elinorbgr** [comment]
Hmm, yeah indeed. Thanks for pointing this out.

I'll tackle this as soon as I have some time, it should be pretty straightforward.

**Comment by elinorbgr** [comment]
Hmm... After some digging, I can't find a way to create a memory-map from a linux file descriptor in memmap-rs, which is exactly the feature I'm using in mmap: https://github.com/vberger/wayland-kbd/blob/master/src/mapped_keyboard.rs#L153-L156

**Comment by retep998** [comment]
@danburkert Nudge, nudge.

**Comment by retep998** [comment]
Wait, you can do this already. On unix platforms you have `FromRawFd` impl'd on `File` so you can use that to get a `File` which you can then pass to memmap.

**Comment by danburkert** [comment]
Yah the `Mmap::open_with_offset` function should work.  That being said, I've never tested against non-file-backed 'files'.

**Comment by elinorbgr** [comment]
Fair point. I'll try this tomorrow.

**Comment by frewsxcv** [comment]
@vberger Did you ever look into this? Did it end up being non-trivial?

**Comment by elinorbgr** [comment]
Hmm, kinda forgot this, sorry for that...

I won't have time to spend on it for the next two weeks unfortunately... :-/

**Comment by frewsxcv** [comment]
> I won't have time to spend on it for the next two weeks unfortunately... :-/

All good!

Opened a PR for this whenever you have time: https://github.com/vberger/wayland-kbd/pull/9
